# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege_level', models.IntegerField()),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logreg.User')),
            ],
        ),
    ]
